# **Introduction to Pandas dataframe: Create and combine dataframes**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, I will be showing you how to create and combine dataframes.

---

### **Import library**

In [1]:
import pandas as pd

### **List of data**

In [2]:
actual = [16.8, 23.9, 13.8, 20.5, 11.3, 19.5,  6.3, 17.9, 13.1, 50. , 21.4,
       19.1, 23.5, 27.9, 37.2, 32.4, 23.8, 20.2, 22.6, 26.6, 23.2, 18.1,
       13.5, 22.9, 21.6, 20. , 30.8,  8.3, 33.3, 25. , 19.4, 36.1, 50. ,
       20.1, 22.8, 12.6, 16.7, 17.8, 22. , 29.1, 21. , 24.5, 50. , 13.3,
       23.4, 50. , 48.8,  5. , 28.7, 16.6, 44. , 16.1, 14.8, 20.3, 23.3,
       22.9, 13. , 18.5, 42.3, 25. , 13.1, 23.9, 16. , 19.8, 18.4, 31.6,
       16.1, 24.5,  7.2, 15.6, 20.5, 19.5, 15.2, 20.6,  8.4,  7. , 21.7,
       30.3, 50. ,  8.7, 17.1, 21.1, 20.1, 20.8, 10.4, 23.6, 23.7, 19.9,
       14.3, 19.2, 29.6, 34.7, 50. , 20.4, 20.1, 26.6, 17.1, 33.4, 11.7,
       21.7, 27.1, 20.2]

In [3]:
predicted = [20.5148569 , 27.82886233, 16.43203562, 24.01932616, 13.81306244,
       20.0544133 , 11.07760091,  1.23841981, 13.08369099, 32.06065051,
       21.80028245, 19.70086401, 30.34151955, 31.96783871, 32.77942469,
       35.48586342, 24.88051126, 16.20186816, 19.63436548, 27.63436029,
       25.55239401, 16.96598602, 13.66610108, 20.76722385, 25.42433781,
       16.68188504, 31.50094734, 13.28704755, 35.77302955, 25.10014145,
       17.04436579, 33.3090196 , 24.85372303, 23.80015208, 26.18331751,
       18.45292525, 19.66103179, 22.55104514, 21.46000897, 31.31314465,
       21.28161596, 20.61125037, 43.90556977, 15.95012827, 23.61341091,
       35.59706661, 40.6356739 ,  6.84204098, 25.38718276, 18.07038018,
       37.33364745, 18.46343365, 14.81861342, 21.98221655, 25.90126042,
       22.94534806, 17.30656894, 19.63037965, 36.71028099, 24.35718345,
       20.46550413, 26.99445794, 18.97647788, 22.60476792, 19.73474778,
       32.1264391 , 18.85756175, 21.42074179,  8.49086946, 12.79200836,
       20.10601397, 18.60872483, 11.07256759, 19.4576125 , 14.02077952,
       -4.47472295, 22.7001417 , 32.28715798, 35.73002861,  8.37161207,
       19.01144658, 22.3577413 , 15.03428522, 22.84082071, 14.00768463,
       30.46514491, 10.99390946, 20.19173782, 13.88027366, 23.47393447,
       24.95657711, 30.22290055, 36.09347373, 20.72634294, 21.429171  ,
       22.34773591, 19.95869185, 35.61725504, 13.81990247, 23.89717481,
       19.56498843, 22.66245896]

In [4]:
type(actual)

list

In [5]:
type(predicted)

list

### **Create pandas dataframe**

In [6]:
Actual = pd.DataFrame(actual)
Actual

        0
0    16.8
1    23.9
2    13.8
3    20.5
4    11.3
..    ...
97   33.4
98   11.7
99   21.7
100  27.1
101  20.2

[102 rows x 1 columns]

In [7]:
Predicted = pd.DataFrame(predicted)
Predicted

             0
0    20.514857
1    27.828862
2    16.432036
3    24.019326
4    13.813062
..         ...
97   35.617255
98   13.819902
99   23.897175
100  19.564988
101  22.662459

[102 rows x 1 columns]

### **Rename columns of pandas dataframe**

In [8]:
Actual.columns = ['Actual']
Actual

     Actual
0      16.8
1      23.9
2      13.8
3      20.5
4      11.3
..      ...
97     33.4
98     11.7
99     21.7
100    27.1
101    20.2

[102 rows x 1 columns]

In [9]:
Predicted.columns = ['Predicted']
Predicted

     Predicted
0    20.514857
1    27.828862
2    16.432036
3    24.019326
4    13.813062
..         ...
97   35.617255
98   13.819902
99   23.897175
100  19.564988
101  22.662459

[102 rows x 1 columns]

### **Combine dataframes**

#### Side-by-side

To combine 2 dataframes we will be using the **pd.concat()** function from pandas. As arguments we specify the 2 input dataframes to combine in brackets; and we also use axis=1 so that the 2 dataframes can be combined side by side.

In [10]:
results = pd.concat([Actual, Predicted], axis=1)
results

     Actual  Predicted
0      16.8  20.514857
1      23.9  27.828862
2      13.8  16.432036
3      20.5  24.019326
4      11.3  13.813062
..      ...        ...
97     33.4  35.617255
98     11.7  13.819902
99     21.7  23.897175
100    27.1  19.564988
101    20.2  22.662459

[102 rows x 2 columns]

#### Stacked vertically

When the axis=0 the 2 dataframes will be stacked vertically.

In [11]:
pd.concat([Actual, Predicted], axis=0)

     Actual  Predicted
0      16.8        NaN
1      23.9        NaN
2      13.8        NaN
3      20.5        NaN
4      11.3        NaN
..      ...        ...
97      NaN  35.617255
98      NaN  13.819902
99      NaN  23.897175
100     NaN  19.564988
101     NaN  22.662459

[204 rows x 2 columns]

In [12]:
Actual2 = Actual
Actual2

     Actual
0      16.8
1      23.9
2      13.8
3      20.5
4      11.3
..      ...
97     33.4
98     11.7
99     21.7
100    27.1
101    20.2

[102 rows x 1 columns]

In [13]:
pd.concat([Actual, Actual2], axis=0)

     Actual
0      16.8
1      23.9
2      13.8
3      20.5
4      11.3
..      ...
97     33.4
98     11.7
99     21.7
100    27.1
101    20.2

[204 rows x 1 columns]

In [14]:
# export to file

results

     Actual  Predicted
0      16.8  20.514857
1      23.9  27.828862
2      13.8  16.432036
3      20.5  24.019326
4      11.3  13.813062
..      ...        ...
97     33.4  35.617255
98     11.7  13.819902
99     21.7  23.897175
100    27.1  19.564988
101    20.2  22.662459

[102 rows x 2 columns]

In [18]:
results.to_csv("results.csv", index = False)

In [22]:
# download many files
! zip results.zip *.csv

  adding: results.csv (deflated 50%)